name: "codeql-actions"
description: "CodeQL Pack for GitHub Actions and Workflows"

inputs:
  token:
    description: GitHub Token
    default: ${{ github.token }}

  source-root:
    description: "Path of the root source code directory, relative to $GITHUB_WORKSPACE."
    default: ${{ github.workspace }}

  sarif-output:
    description: "SARIF File Output"
    default: "codeql-actions.sarif"

  suite:
    description: "CodeQL Suite to run"
    default: "actions-code-scanning"

  workflow-models:
    description: "Workflow models"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Process workflow models
      shell: bash
      if: inputs.workflow-models
      run: |
        # Create QLPack directory
        mkdir workflow-extpack
        cd workflow-extpack

        # Store the extension pack file
        cat > models.yml << 'EOF'
        ${{ inputs.workflow-models }}
        EOF

        # Create QLPack
        cat > qlpack.yml << 'EOF'
        name: local/workflow-models
        library: true
        extensionTargets:
          githubsecuritylab/actions-all: '*'
        dataExtensions:
          - models.yml
        EOF

        # Set env vars
        echo "EXTPACK_PATH=./workflow-extpack" >> $GITHUB_ENV
        echo "EXTPACK_NAME=local/workflow-models" >> $GITHUB_ENV
       
    - name: Scan workflows 
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GH_TOKEN: ${{ inputs.token }}
        INPUT_SOURCE-ROOT: ${{ inputs.source-root }}
        INPUT_SARIF-OUTPUT: ${{ inputs.sarif-output }}
        INPUT_SUITE: ${{ inputs.suite }}
        EXTPACK_PATH: ${{ env.EXTPACK_PATH }}
        EXTPACK_NAME: ${{ env.EXTPACK_NAME }}
      run: |
        node ${{ github.action_path }}/.github/action/dist/index.js
