name: "codeql-actions"
description: "CodeQL Pack for GitHub Actions and Workflows"

inputs:
  token:
    description: GitHub Token
    default: ${{ github.token }}
  source-root:
    description: "Path of the root source code directory, relative to $GITHUB_WORKSPACE."
    default: ${{ github.workspace }}
  sarif-output:
    description: "SARIF File Output"
    default: "codeql-actions.sarif"
  suite:
    description: "CodeQL Suite to run"
    default: "actions-code-scanning"
  workflow-extpack-path:
    description: "Path to Workflow extpack"
    required: false
  workflow-extpack-name:
    description: "Name of the Workflow extpack"
    required: false

runs:
  using: 'composite'
  steps:
    - name: extpack contents
      shell: bash
      env:
        EXTPACK_PATH: ${{ inputs.workflow-extpack-path }}
        EXTPACK_NAME: ${{ inputs.workflow-extpack-name }}
      run: |
        echo "##[group] Workflow Models"
        if [ -f $EXTPACK_PATH/models.yml ]; then cat $EXTPACK_PATH/models.yml; fi
        echo "##[endgroup]"
        echo "##[group] QLPack"
        if [ -f $EXTPACK_PATH/qlpack.yml ]; then cat $EXTPACK_PATH/qlpack.yml; fi
        echo "##[endgroup]"

    - name: Scan workflows 
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GH_TOKEN: ${{ inputs.token }}
        INPUT_SOURCE-ROOT: ${{ inputs.source-root }}
        INPUT_SARIF-OUTPUT: ${{ inputs.sarif-output }}
        INPUT_SUITE: ${{ inputs.suite }}
        EXTPACK_PATH: ${{ inputs.workflow-extpack-path }}
        EXTPACK_NAME: ${{ inputs.workflow-extpack-name }}
      run: |
        node ${{ github.action_path }}/.github/action/dist/index.js
