name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BUGHALLA_TOKEN }}
          fetch-depth: 0
      
      - run: |
          codeql test run ql/test
