name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        id: init
        run: |
          # Take the most modern version
          VERSION="$(find "${{ runner.tool_cache }}/CodeQL/" -maxdepth 1 -mindepth 1 -type d -print \
                     | sort \
                     | tail -n 1 \
                     | tr -d '\n')"

          CODEQL="$VERSION/x64/codeql/"
          "${CODEQL}"/codeql version --format=json
          echo "${CODEQL}" >> $GITHUB_PATH
      - run: |
          codeql pack install ql/test
          codeql test run ql/test
